//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIProjectEX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Garage_of_carsEntities1 : DbContext
    {
        public Garage_of_carsEntities1()
            : base("name=Garage_of_carsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Status> Employee_Status { get; set; }
        public virtual DbSet<Mishap_Status> Mishap_Status { get; set; }
        public virtual DbSet<Mishaps> Mishaps { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Mishap_To_Worker> Mishap_To_Worker { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
