//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mishap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mishap()
        {
            this.Mishap_for_employee = new HashSet<Mishap_for_employee>();
        }
    
        public int mishap_code { get; set; }
        public string car_number { get; set; }
        public string mishap_description { get; set; }
        public int num_of_credits { get; set; }
        public int mishap_urgency { get; set; }
        public int mishap_status_code { get; set; }
        public double mishap_price { get; set; }
    
        public virtual Car Car { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mishap_for_employee> Mishap_for_employee { get; set; }
        public virtual Mishap_status Mishap_status { get; set; }
    }
}
